# -*- coding: utf-8 -*-
"""Copy of Social Media ads classifier(KNN).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bB7U2xuWV5c8RK1OpR3bUx69e6jdC14x
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv('Adds.csv')
dataset.head()

dataset.tail()

len(dataset)

print(dataset.isnull().sum())

"""There are no null values in the dataset"""

#dataset["Purchased"] = (dataset["Purchased"] == 1). astype(int)
#plt.hist(dataset["Purchased"]==1, color = 'blue', label= 'Purchased')
dataset.dtypes

plt.figure(figsize=(10, 5))
plt.title("Product Purchased By People Through Social Media Marketing")
sns.histplot(x="Age", hue="Purchased", data=dataset)
plt.show()

plt.title("Product Purchased By People According to Their Income")
sns.histplot(x="EstimatedSalary", hue="Purchased", data=dataset)
plt.show()

x= dataset.iloc[:, 0:2]
y= dataset.iloc[:,2]
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state = 0, test_size = 0.2)

sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

classifier = KNeighborsClassifier(n_neighbors = 3, p=2, metric = 'euclidean')
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test,y_pred)
print(cm)

print(f1_score(y_test,y_pred))

print(accuracy_score(y_test,y_pred))